title: Techayurveda
author: Priyal Pratik
email: vdpratikmehta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site of Ancient Ayurveda and Modern Technology. 

# social link
twitter_username: PriyalMehta44 #lude the @ character, or else the build will fail!
github_username:  priyal44 # DO NOT include the @ character, or else the build will fail!

show_excerpts: Rejuvenate yourself with Modern Ayurveda.  # set to false to remove excerpts on the homepage
theme: jekyll-theme-midnight
